package com.cyb.tms.entity;
// Generated May 17, 2016 12:38:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmsLeaveMst generated by hbm2java
 */
@Entity
@Table(name = "tms_leave_mst", catalog = "TaskManagement")
public class TmsLeaveMst implements java.io.Serializable {

	private Long leaveId;
	private TmsSprintMst tmsSprintMst;
	private TmsUsers tmsUsers;
	private Date date;
	private String leavetype;

	public TmsLeaveMst() {
	}

	public TmsLeaveMst(TmsSprintMst tmsSprintMst, TmsUsers tmsUsers, Date date, String leavetype) {
		this.tmsSprintMst = tmsSprintMst;
		this.tmsUsers = tmsUsers;
		this.date = date;
		this.leavetype = leavetype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_ID", unique = true, nullable = false)
	public Long getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(Long leaveId) {
		this.leaveId = leaveId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPRINTID", nullable = false)
	public TmsSprintMst getTmsSprintMst() {
		return this.tmsSprintMst;
	}

	public void setTmsSprintMst(TmsSprintMst tmsSprintMst) {
		this.tmsSprintMst = tmsSprintMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public TmsUsers getTmsUsers() {
		return this.tmsUsers;
	}

	public void setTmsUsers(TmsUsers tmsUsers) {
		this.tmsUsers = tmsUsers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "LEAVETYPE", nullable = false, length = 9)
	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

}
