package com.cyb.tms.entity;
// Generated May 17, 2016 12:38:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * TmsProject generated by hbm2java
 */
@Entity
@Table(name = "tms_project", catalog = "TaskManagement")
public class TmsProject extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -807529177177062214L;
	private Long pid;
	private String name;
	private Date startDate;
	private String projectDesc;
	private Date endDate;
	private Set<TmsModule> tmsModules = new HashSet<TmsModule>(0);

	public TmsProject() {
	}

	public TmsProject(String name, Date startDate, String projectDesc, Date endDate, Set<TmsModule> tmsModules) {
		this.name = name;
		this.startDate = startDate;
		this.projectDesc = projectDesc;
		this.endDate = endDate;
		this.tmsModules = tmsModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PID", unique = true, nullable = false)
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "PROJECT_DESC", length = 100)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsProject")
	public Set<TmsModule> getTmsModules() {
		return this.tmsModules;
	}

	public void setTmsModules(Set<TmsModule> tmsModules) {
		this.tmsModules = tmsModules;
	}

}
