package com.cyb.tms.entity;
// Generated May 12, 2016 11:55:51 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * TmsSprintUser generated by hbm2java
 */
@Entity
@Table(name = "tms_sprint_user", catalog = "TaskManagement")
public class TmsSprintUser extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5338083274424774476L;
	private Long id;
	private TmsSprintMst tmsSprintMst;
	private TmsUsers tmsUsers;

	public TmsSprintUser() {
	}

	public TmsSprintUser(TmsSprintMst tmsSprintMst, TmsUsers tmsUsers) {
		this.tmsSprintMst = tmsSprintMst;
		this.tmsUsers = tmsUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPRINT", nullable = false)
	public TmsSprintMst getTmsSprintMst() {
		return this.tmsSprintMst;
	}

	public void setTmsSprintMst(TmsSprintMst tmsSprintMst) {
		this.tmsSprintMst = tmsSprintMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER", nullable = false)
	public TmsUsers getTmsUsers() {
		return this.tmsUsers;
	}

	public void setTmsUsers(TmsUsers tmsUsers) {
		this.tmsUsers = tmsUsers;
	}

}
