package com.cyb.tms.entity;
// Generated May 12, 2016 11:55:51 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * TmsStatusMst generated by hbm2java
 */
@Entity
@Table(name = "tms_status_mst", catalog = "TaskManagement")
public class TmsStatusMst extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1665371766283980783L;
	private Long statusId;
	private String status;
	private Set<TmsStoryMst> tmsStoryMsts = new HashSet<TmsStoryMst>(0);
	private Set<UserStoryStaus> userStoryStauses = new HashSet<UserStoryStaus>(0);

	public TmsStatusMst() {
	}

	public TmsStatusMst(String status) {
		this.status = status;
	}

	public TmsStatusMst(String status, Set<TmsStoryMst> tmsStoryMsts, Set<UserStoryStaus> userStoryStauses) {
		this.status = status;
		this.tmsStoryMsts = tmsStoryMsts;
		this.userStoryStauses = userStoryStauses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public Long getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Long statusId) {
		this.statusId = statusId;
	}

	@Column(name = "STATUS", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsStatusMst")
	public Set<TmsStoryMst> getTmsStoryMsts() {
		return this.tmsStoryMsts;
	}

	public void setTmsStoryMsts(Set<TmsStoryMst> tmsStoryMsts) {
		this.tmsStoryMsts = tmsStoryMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsStatusMst")
	public Set<UserStoryStaus> getUserStoryStauses() {
		return this.userStoryStauses;
	}

	public void setUserStoryStauses(Set<UserStoryStaus> userStoryStauses) {
		this.userStoryStauses = userStoryStauses;
	}

}
