package com.cyb.tms.entity;
// Generated May 17, 2016 12:38:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * TmsSubtask generated by hbm2java
 */
@Entity
@Table(name = "tms_subtask", catalog = "TaskManagement")
public class TmsSubtask extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9222900952318082035L;
	private Long subtaskId;
	private TmsStoryMst tmsStoryMst;
	private TmsUsers tmsUsers;
	private Date assignedDate;
	private Date createdDate;
	private int efforts;
	private String jiraId;
	private String scope;
	private String type;
	private Set<TmsCodeReview> tmsCodeReviews = new HashSet<TmsCodeReview>(0);
	private Set<TmsEfforts> tmsEffortses = new HashSet<TmsEfforts>(0);

	public TmsSubtask() {
	}

	public TmsSubtask(TmsStoryMst tmsStoryMst, TmsUsers tmsUsers, Date assignedDate, Date createdDate, int efforts,
			String jiraId, String scope, String type) {
		this.tmsStoryMst = tmsStoryMst;
		this.tmsUsers = tmsUsers;
		this.assignedDate = assignedDate;
		this.createdDate = createdDate;
		this.efforts = efforts;
		this.jiraId = jiraId;
		this.scope = scope;
		this.type = type;
	}

	public TmsSubtask(TmsStoryMst tmsStoryMst, TmsUsers tmsUsers, Date assignedDate, Date createdDate, int efforts,
			String jiraId, String scope, String type, Set<TmsCodeReview> tmsCodeReviews, Set<TmsEfforts> tmsEffortses) {
		this.tmsStoryMst = tmsStoryMst;
		this.tmsUsers = tmsUsers;
		this.assignedDate = assignedDate;
		this.createdDate = createdDate;
		this.efforts = efforts;
		this.jiraId = jiraId;
		this.scope = scope;
		this.type = type;
		this.tmsCodeReviews = tmsCodeReviews;
		this.tmsEffortses = tmsEffortses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SUBTASK_ID", unique = true, nullable = false)
	public Long getSubtaskId() {
		return this.subtaskId;
	}

	public void setSubtaskId(Long subtaskId) {
		this.subtaskId = subtaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STORY_ID", nullable = false)
	public TmsStoryMst getTmsStoryMst() {
		return this.tmsStoryMst;
	}

	public void setTmsStoryMst(TmsStoryMst tmsStoryMst) {
		this.tmsStoryMst = tmsStoryMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSIGNED_USER", nullable = false)
	public TmsUsers getTmsUsers() {
		return this.tmsUsers;
	}

	public void setTmsUsers(TmsUsers tmsUsers) {
		this.tmsUsers = tmsUsers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASSIGNED_DATE", nullable = false, length = 10)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "EFFORTS", nullable = false)
	public int getEfforts() {
		return this.efforts;
	}

	public void setEfforts(int efforts) {
		this.efforts = efforts;
	}

	@Column(name = "JIRA_ID", nullable = false, length = 45)
	public String getJiraId() {
		return this.jiraId;
	}

	public void setJiraId(String jiraId) {
		this.jiraId = jiraId;
	}

	@Column(name = "SCOPE", nullable = false, length = 10)
	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name = "TYPE", nullable = false, length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsSubtask")
	public Set<TmsCodeReview> getTmsCodeReviews() {
		return this.tmsCodeReviews;
	}

	public void setTmsCodeReviews(Set<TmsCodeReview> tmsCodeReviews) {
		this.tmsCodeReviews = tmsCodeReviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsSubtask")
	public Set<TmsEfforts> getTmsEffortses() {
		return this.tmsEffortses;
	}

	public void setTmsEffortses(Set<TmsEfforts> tmsEffortses) {
		this.tmsEffortses = tmsEffortses;
	}

}
