package com.cyb.tms.entity;
// Generated May 12, 2016 11:55:51 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cyb.tms.entity.base.BaseEntity;

/**
 * UserStoryStaus generated by hbm2java
 */
@Entity
@Table(name = "user_story_staus", catalog = "TaskManagement")
public class UserStoryStaus extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1330920914636441225L;
	private Long id;
	private TmsStatusMst tmsStatusMst;
	private TmsUsers tmsUsers;
	private String jiraId;
	private Date modifiedDate;
	private String type;

	public UserStoryStaus() {
	}

	public UserStoryStaus(TmsStatusMst tmsStatusMst, TmsUsers tmsUsers, String jiraId, Date modifiedDate, String type) {
		this.tmsStatusMst = tmsStatusMst;
		this.tmsUsers = tmsUsers;
		this.jiraId = jiraId;
		this.modifiedDate = modifiedDate;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public TmsStatusMst getTmsStatusMst() {
		return this.tmsStatusMst;
	}

	public void setTmsStatusMst(TmsStatusMst tmsStatusMst) {
		this.tmsStatusMst = tmsStatusMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY", nullable = false)
	public TmsUsers getTmsUsers() {
		return this.tmsUsers;
	}

	public void setTmsUsers(TmsUsers tmsUsers) {
		this.tmsUsers = tmsUsers;
	}

	@Column(name = "JIRA_ID", nullable = false, length = 20)
	public String getJiraId() {
		return this.jiraId;
	}

	public void setJiraId(String jiraId) {
		this.jiraId = jiraId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "TYPE", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
